# Stable rustfmt configuration
reorder_imports = true

tab_spaces = 4
hard_tabs = true

max_width = 90
fn_call_width = 80

use_field_init_shorthand = true

# Note: The following options require nightly rustfmt:
# indent_style = "Block"
# group_imports = "StdExternalCrate" 
# imports_granularity = "Module"
